apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: licenta
  name: licenta-api-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: licenta-api-backend
  template:
    metadata:
      labels:
        app: licenta-api-backend
    spec:
      containers:
      - name: licenta-api-backend
        image: api-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  namespace: licenta
  name: licenta-backend-api-service
spec:
  type: NodePort
  selector:
    app: licenta-api-backend
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
